version: 2.1
orbs:
  ruby: circleci/ruby@1.0.0
  ruby-linter: amyroi/ruby-linter@1.0.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7
    steps:
      - checkout
      - ruby/install:
          version: '2.7'
      - run: echo "Ruby 2.7 has been installed"
      - run:
        name: Install bundler
        command: gem install bundler:2.1.4
      - run: bundle install

      - ruby-linter/rubocop:
          files: app/**/*.rb lib/**/*.rb config/**/*.rb spec/**/*.rb script/**/*.rb
          report_dir: $CIRCLE_TEST_REPORTS
