version: 2.1
orbs:
  ruby: circleci/ruby@1.0.0

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7
    steps:
      - checkout
      - ruby/install:
          version: '2.7'
      - run: echo "Ruby 2.7 has been installed"
      - run:
          name: Install bundler
          command: gem install bundler:2.1.4
      - run: bundle install
      - run:
          name: Rubocop checks
          command: git diff-tree -r --no-commit-id --name-only head origin/master | xargs rubocop
